language: php

php:
  - 7.3
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.3
      env: PHPCS=1 DEFAULT=0

    - php: 7.3
      env: PHPSTAN=1 DEFAULT=0

before_script:
  - if [[ $DEFAULT == 1 || $PHPCS == 1 ]]; then composer update; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS == 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN == 1 ]]; then vendor/bin/phpstan analyse src/; fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
