<?php

$generalJs = array();
$generalJs[] = PUBLICURL . 'components/jquery/dist/jquery.js';
/*$generalJs[] = PUBLICURL . 'components/jquery-ui/ui/effect.js';
$generalJs[] = PUBLICURL . 'components/jquery-ui/ui/effect-pulsate.js';
$generalJs[] = PUBLICURL . 'components/bootstrap/js/transition.js';
$generalJs[] = PUBLICURL . 'components/bootstrap/js/collapse.js';
$generalJs[] = PUBLICURL . 'components/bootstrap/js/dropdown.js';*/
$generalJs[] = PUBLICURL . 'components/matchmedia/matchMedia.js';
$generalJs[] = PUBLICURL . 'components/matchmedia/matchMedia.addListener.js';
$generalJs[] = PUBLICURL . 'components/enquire/dist/enquire.js';
//$generalJs[] = 'https://storage.googleapis.com/code.getmdl.io/1.0.5/material.min.js';
$generalJs[] = PUBLICURL . 'components/material-design-lite/src/mdlComponentHandler.js';
$generalJs[] = PUBLICURL . 'components/material-design-lite/src/layout/layout.js';
$generalJs[] = PUBLICURL . 'components/material-design-lite/src/tabs/tabs.js';
$generalJs[] = PUBLICURL . 'components/material-design-lite/src/checkbox/checkbox.js';
$generalJs[] = PUBLICURL . 'components/material-design-lite/src/data-table/data-table.js';
$generalJs[] = PUBLICURL . 'components/material-design-lite/src/button/button.js';
$generalJs[] = PUBLICURL . 'components/material-design-lite/src/ripple/ripple.js';
$generalJs[] = PUBLICURL . 'components/material-design-lite/src/menu/menu.js';
$generalJs[] = PUBLICURL . 'components/material-design-lite/src/spinner/spinner.js';
$generalJs[] = PUBLICURL . 'components/material-design-lite/src/snackbar/snackbar.js';
$generalJs[] = PUBLICURL . 'components/material-design-lite/src/textfield/textfield.js';
//$generalJs[] = PUBLICURL . 'components/sticky/jquery.sticky.js';
//$generalJs[] = PUBLICURL . 'components/bootstrap/js/affix.js';
//$generalJs[] = JSURL . 'syze/syze.js';
//$generalJs[] = JSURL . 'stickyPanel/jquery.stickyPanel.js';
$generalJs[] = JSURL . 'modernizr/modernizr.js';
/*$generalJs[] = JSURL . 'countdown/jquery.jcountdown1.3.js';
//$generalJs[] = JSURL . 'googleAnalytics/googleAnalytics.js';*/
$generalJs[] = JSURL . 'custom/all.js';

$generalCss = array();
//$generalCss[] = 'bootstrap/bootstrap';
//$generalCss[] = 'layout';
//$generalCss[] = 'style';
//$generalCss[] = 'fancybox';
$generalCss[] = 'main';
